// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package config

import (
	"github.com/gileslloyd/menu-parser/internal/app/controller"
	"github.com/gileslloyd/menu-parser/internal/domain/menu"
	"github.com/gileslloyd/menu-parser/pkg/infrastructure/cloudvision"
)

// Injectors from container.go:

func CreateMenuController() controller.Menu {
	imageParser := cloudvision.NewMLParser()
	service := menu.NewService(imageParser)
	controllerMenu := controller.NewMenuController(service)
	return controllerMenu
}
