// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package config

import (
	"github.com/gileslloyd/menu-parser/internal/app/controller"
	"github.com/gileslloyd/menu-parser/internal/domain/menu"
	"github.com/gileslloyd/menu-parser/pkg/infrastructure/cloudvision"
	"github.com/gileslloyd/menu-parser/pkg/infrastructure/delivery/rpc"
)

// Injectors from container.go:

func CreateMenuController() controller.Menu {
	imageParser := cloudvision.NewMLParser()
	service := menu.NewService(imageParser)
	controllerMenu := controller.NewMenuController(service)
	return controllerMenu
}

func CreateMessageListener() rpc.MessageListener {
	v := GetRoutes()
	handler := rpc.NewHandler(v)
	messageListener := rpc.NewMessageListener(handler)
	return messageListener
}
